// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa5V-Yypd-eRPey-r80EbMLurt_93oLCo',
    appId: '1:562764359620:web:918754381e103d097fe691',
    messagingSenderId: '562764359620',
    projectId: 'notetaking-25382',
    authDomain: 'notetaking-25382.firebaseapp.com',
    storageBucket: 'notetaking-25382.appspot.com',
    databaseURL:
        'https://notetaking-25382-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi4BsHtZ_YI-OiU-v4-gHuNcb0JJrbnWg',
    appId: '1:562764359620:android:eeaee142354c38b97fe691',
    messagingSenderId: '562764359620',
    projectId: 'notetaking-25382',
    storageBucket: 'notetaking-25382.appspot.com',
    databaseURL:
        'https://notetaking-25382-default-rtdb.europe-west1.firebasedatabase.app/',
  );
}
